### ISSUE TITLE
Not working on doom emacs

### ISSUE THREAD

**Issue by eliraz-refael** [Lambda-Emacs/lambda-themes#1]
Duo to the support in lambda-modeline which doom emacs doesn't have, this theme cannot work under doom emacs which is shameful because it looks amazing.

how about adding support to doom-modeline and make it work on doom-emacs as well ? :)

**Comment by mclearc** [comment]
This should be fixed by ee7e325ea8a7fe9924a9996eb7810b96d44cfcb4. Please test when you can and let me know.

**Comment by eliraz-refael** [comment]
confirmed it to be working. thanks!
