### ISSUE TITLE
Readability of faces in elfeed and table.el

### ISSUE THREAD

**Issue by kvvba** [Lambda-Emacs/lambda-themes#2]
At the moment unread items in elfeed and highlighted lines in table.el edit buffer have poor readability when using the faded white theme. In my config the faces I change are:

`(custom-set-faces
 '(elfeed-search-unread-title-face ((t (:foreground "#282b35"))))
 '(table-cell ((t (:background "#fcfaf6" :foreground "#282b35" :inverse-video nil)))))
`

**Comment by mclearc** [comment]
Great - thanks for letting me know. I'll look into this
