### ISSUE TITLE
Error message: Invalid face box

### ISSUE THREAD

**Issue by 9s-l-s9** [Lambda-Emacs/lambda-themes#3]
Hello, 

I tried to use the theme but received the following error message: 

`Error (use-package): lambda-themes/:config: Invalid face box: :line-width, (8 . 2), :color, nil, :style, flat-button`

Am I missing anything? 

Thank you.

**Comment by 9s-l-s9** [comment]
Thank you for your quick reaction. 
After 'straight-pull-package-all' I now get the following error:
`Error (use-package): lambda-themes/:config: Symbol’s function definition is void: \,`

**Comment by 9s-l-s9** [comment]
I now get `Error (use-package): lambda-themes/:config: Invalid face box: :line-width, (2 . 2), :color, "#141414", :style, nil` 😅

**Comment by mclearc** [comment]
lol -- ok apparently the line-width was also a problem. Fixed now (see be856175f478ccb71586499c28e32c26af05589a). And I was able to test it on emacs 27.2 (macos) and it works for me.

**Comment by 9s-l-s9** [comment]
Yep, it works. Thank you, looks great :)
