### ISSUE TITLE
help installing locally

### ISSUE THREAD

**Issue by morphykuffour** [Lambda-Emacs/lambda-themes#6]
I have this repo cloned to my `.emac.d` directory however I am not getting the themes to appear. I tried using straight.el but that was giving errors also. These were the changes I have added to my init.el 
```elisp

(add-to-list  'load-path "~/.emacs.d/lambda-themes")
(require 'lambda-themes)

(use-package circadian
  :ensure t
  :config
  (setq calendar-latitude 53.6)
  (setq calendar-longitude -2.43)
  (setq circadian-themes '((:sunrise . lambda-light)
                           (:sunset  . lambda-dark)))
  (circadian-setup))
```

**Comment by mclearc** [comment]
I don't use circadian. But I don't see why it shouldn't work, as it just uses `load-theme` in the setup process. Can you load any of the lambda-themes just calling e.g. `(load-theme 'lambda-light t)`?
